version: '3'

services:

  # database
  db:
    image: joba-db
    build:
      context: ./docs/db/
    volumes:
    - db:/data/db
    ports:
    - "5432:5432"
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: sohail
      POSTGRES_PASSWORD: joba

  # api server
  api:
    depends_on:
    - db
    image: joba-api
    build:
      context: ./
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: sohail
      POSTGRES_PASSWORD: joba
      POSTGRES_HOST: db
    ports:
    - "8080:8080"

volumes:
  db:
